#!/bin/bash
cd "$(dirname "$0")"
if [ ! -d "env" ]; then
  echo "Creating virtual environment"
  python3 -m venv env
fi

echo "Activating virtual environment"
source env/bin/activate
echo "Installing requirements"
pip install -r requirements.txt

echo "Running app"
python3 main.py

deactivate